name: test

on: push

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/ginkgo@v1.16.5
      - name: Test
        run: ginkgo ./...
